// A1 Unit 6: Places & Directions — Spanish for English Speakers
import { LessonContent } from './a1-lessons';

const lessons: Record<string, LessonContent> = {
  'A1-u06-l01': {
    lessonId: 'A1-u06-l01', passingScore: 70,
    vocab: [
      { english: 'Hospital', arabic: 'Hospital', example: 'El hospital está cerca.', exampleAr: 'The hospital is nearby.' },
      { english: 'School', arabic: 'Escuela', example: 'Voy a la escuela cada día.', exampleAr: 'I go to school every day.' },
      { english: 'Bank', arabic: 'Banco', example: 'El banco abre a las nueve.', exampleAr: 'The bank opens at nine.' },
      { english: 'Supermarket', arabic: 'Supermercado', example: 'Compro en el supermercado.', exampleAr: 'I shop at the supermarket.' },
      { english: 'Pharmacy', arabic: 'Farmacia', example: 'Compra medicinas en la farmacia.', exampleAr: 'Buy medicine at the pharmacy.' },
      { english: 'Restaurant', arabic: 'Restaurante', example: 'Comemos en el restaurante.', exampleAr: 'We eat at the restaurant.' },
      { english: 'Park', arabic: 'Parque', example: 'El parque es bonito.', exampleAr: 'The park is beautiful.' },
      { english: 'Library', arabic: 'Biblioteca', example: 'Leo en la biblioteca.', exampleAr: 'I read at the library.' },
      { english: 'Church', arabic: 'Iglesia', example: 'La iglesia está cerca.', exampleAr: 'The church is nearby.' },
      { english: 'Police station', arabic: 'Comisaría', example: 'Ve a la comisaría.', exampleAr: 'Go to the police station.' },
    ],
    sentences: [
      { english: 'The hospital is nearby.', arabic: 'El hospital está cerca de aquí.' },
      { english: 'I go to school every day.', arabic: 'Voy a la escuela cada día.' },
      { english: 'The bank opens at nine.', arabic: 'El banco abre a las nueve.' },
      { english: 'There is a pharmacy next to the supermarket.', arabic: 'Hay una farmacia al lado del supermercado.' },
      { english: 'The park is beautiful.', arabic: 'El parque es bonito.' },
      { english: 'I read books at the library.', arabic: 'Leo libros en la biblioteca.' },
    ],
    exercises: [
      { type: 'mcq', promptAr: 'What is "hospital" in Spanish?', data: { options: ['Escuela', 'Hospital', 'Farmacia', 'Restaurante'], correct: 1 } },
      { type: 'mcq', promptAr: 'What is "library" in Spanish?', data: { options: ['Escuela', 'Banco', 'Biblioteca', 'Parque'], correct: 2 } },
      { type: 'fill_blank', promptAr: 'Complete: El ___ está cerca. (hospital)', data: { answer: 'hospital' } },
      { type: 'matching', promptAr: 'Match the places', data: { pairs: [{ english: 'Bank', arabic: 'Banco' }, { english: 'Park', arabic: 'Parque' }, { english: 'Church', arabic: 'Iglesia' }, { english: 'Restaurant', arabic: 'Restaurante' }] } },
      { type: 'reorder', promptAr: 'Arrange: es / El / bonito / parque', data: { words: ['El', 'parque', 'es', 'bonito'], correctOrder: [0, 1, 2, 3] } },
      { type: 'mcq', promptAr: 'Where do you buy medicine?', data: { options: ['Biblioteca', 'Farmacia', 'Banco', 'Parque'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: Leo libros en la ___.', data: { answer: 'biblioteca' } },
      { type: 'translation', promptAr: 'Translate to Spanish: The church is nearby', data: { answer: 'La iglesia está cerca', alternatives: ['la iglesia está cerca'] } },
    ],
    quiz: [
      { type: 'mcq', promptAr: 'What is "supermarket" in Spanish?', data: { options: ['Farmacia', 'Supermercado', 'Restaurante', 'Banco'], correct: 1 }, points: 15 },
      { type: 'mcq', promptAr: 'What is "park" in Spanish?', data: { options: ['Jardín', 'Parque', 'Bosque', 'Granja'], correct: 1 }, points: 15 },
      { type: 'fill_blank', promptAr: 'Complete: El ___ abre a las nueve. (bank)', data: { answer: 'banco' }, points: 20 },
      { type: 'matching', promptAr: 'Match the places', data: { pairs: [{ english: 'Hospital', arabic: 'Hospital' }, { english: 'School', arabic: 'Escuela' }, { english: 'Pharmacy', arabic: 'Farmacia' }] }, points: 25 },
      { type: 'translation', promptAr: 'Translate to Spanish: I go to school every day', data: { answer: 'Voy a la escuela cada día', alternatives: ['Yo voy a la escuela cada día'] }, points: 25 },
    ]
  },
  'A1-u06-l02': {
    lessonId: 'A1-u06-l02', passingScore: 70,
    vocab: [
      { english: 'Right', arabic: 'Derecha', example: 'Gira a la derecha aquí.', exampleAr: 'Turn right here.' },
      { english: 'Left', arabic: 'Izquierda', example: 'Gira a la izquierda en la esquina.', exampleAr: 'Turn left at the corner.' },
      { english: 'Straight', arabic: 'Recto / Derecho', example: 'Sigue recto.', exampleAr: 'Go straight ahead.' },
      { english: 'Near', arabic: 'Cerca', example: 'El banco está cerca.', exampleAr: 'The bank is near.' },
      { english: 'Far', arabic: 'Lejos', example: 'No está lejos.', exampleAr: 'It is not far.' },
      { english: 'Next to', arabic: 'Al lado de', example: 'El banco está al lado de la farmacia.', exampleAr: 'The bank is next to the pharmacy.' },
      { english: 'Behind', arabic: 'Detrás de', example: 'La escuela está detrás de la iglesia.', exampleAr: 'The school is behind the church.' },
      { english: 'In front of', arabic: 'Delante de / Enfrente de', example: 'El coche está delante de la casa.', exampleAr: 'The car is in front of the house.' },
      { english: 'Between', arabic: 'Entre', example: 'El parque está entre el hospital y la biblioteca.', exampleAr: 'The park is between the hospital and the library.' },
      { english: 'Corner', arabic: 'Esquina', example: 'Gira en la esquina.', exampleAr: 'Turn at the corner.' },
    ],
    sentences: [
      { english: 'Turn right at the corner.', arabic: 'Gira a la derecha en la esquina.' },
      { english: 'Go straight ahead.', arabic: 'Sigue recto.' },
      { english: 'The bank is next to the pharmacy.', arabic: 'El banco está al lado de la farmacia.' },
      { english: 'The school is behind the church.', arabic: 'La escuela está detrás de la iglesia.' },
      { english: 'It is not far from here.', arabic: 'No está lejos de aquí.' },
      { english: 'The park is between the hospital and the library.', arabic: 'El parque está entre el hospital y la biblioteca.' },
    ],
    exercises: [
      { type: 'mcq', promptAr: 'What is "right" in Spanish?', data: { options: ['Izquierda', 'Derecha', 'Recto', 'Detrás'], correct: 1 } },
      { type: 'mcq', promptAr: 'What is "next to" in Spanish?', data: { options: ['Detrás de', 'Delante de', 'Al lado de', 'Entre'], correct: 2 } },
      { type: 'fill_blank', promptAr: 'Complete: Gira a la ___ en la esquina. (right)', data: { answer: 'derecha' } },
      { type: 'matching', promptAr: 'Match the directions', data: { pairs: [{ english: 'Left', arabic: 'Izquierda' }, { english: 'Straight', arabic: 'Recto' }, { english: 'Near', arabic: 'Cerca' }, { english: 'Far', arabic: 'Lejos' }] } },
      { type: 'reorder', promptAr: 'Arrange: recto / Sigue', data: { words: ['Sigue', 'recto'], correctOrder: [0, 1] } },
      { type: 'mcq', promptAr: 'What is the opposite of "cerca"?', data: { options: ['Izquierda', 'Derecha', 'Lejos', 'Recto'], correct: 2 } },
      { type: 'fill_blank', promptAr: 'Complete: La escuela está ___ de la iglesia. (behind)', data: { answer: 'detrás' } },
      { type: 'translation', promptAr: 'Translate to Spanish: Go straight ahead', data: { answer: 'Sigue recto', alternatives: ['sigue recto', 'Sigue derecho'] } },
    ],
    quiz: [
      { type: 'mcq', promptAr: 'What is "left" in Spanish?', data: { options: ['Derecha', 'Izquierda', 'Recto', 'Cerca'], correct: 1 }, points: 15 },
      { type: 'mcq', promptAr: 'What is "behind" in Spanish?', data: { options: ['Delante de', 'Al lado de', 'Detrás de', 'Entre'], correct: 2 }, points: 15 },
      { type: 'fill_blank', promptAr: 'Complete: No está ___ de aquí. (far)', data: { answer: 'lejos' }, points: 20 },
      { type: 'matching', promptAr: 'Match the directions', data: { pairs: [{ english: 'Corner', arabic: 'Esquina' }, { english: 'Between', arabic: 'Entre' }, { english: 'In front of', arabic: 'Delante de' }] }, points: 25 },
      { type: 'translation', promptAr: 'Translate to Spanish: The bank is next to the pharmacy', data: { answer: 'El banco está al lado de la farmacia', alternatives: ['el banco está al lado de la farmacia'] }, points: 25 },
    ]
  },
  'A1-u06-l03': {
    lessonId: 'A1-u06-l03', passingScore: 70,
    vocab: [
      { english: 'Where', arabic: 'Dónde', example: '¿Dónde está el hospital?', exampleAr: 'Where is the hospital?' },
      { english: 'How', arabic: 'Cómo', example: '¿Cómo llego allí?', exampleAr: 'How do I get there?' },
      { english: 'Excuse me', arabic: 'Disculpe', example: 'Disculpe, ¿dónde está el banco?', exampleAr: 'Excuse me, where is the bank?' },
      { english: 'Can you help', arabic: '¿Puede ayudarme?', example: '¿Puede ayudarme, por favor?', exampleAr: 'Can you help me please?' },
      { english: 'I am looking for', arabic: 'Estoy buscando', example: 'Estoy buscando el banco.', exampleAr: 'I am looking for the bank.' },
      { english: 'I am lost', arabic: 'Estoy perdido/a', example: 'Estoy perdido. ¿Puede ayudarme?', exampleAr: 'I am lost. Can you help?' },
      { english: 'Which way', arabic: '¿Por dónde?', example: '¿Por dónde se va al parque?', exampleAr: 'Which way to the park?' },
      { english: 'Address', arabic: 'Dirección', example: '¿Cuál es tu dirección?', exampleAr: 'What is your address?' },
      { english: 'Map', arabic: 'Mapa', example: '¿Tienes un mapa?', exampleAr: 'Do you have a map?' },
      { english: 'Thank you', arabic: 'Gracias', example: 'Gracias por tu ayuda.', exampleAr: 'Thank you for your help.' },
    ],
    sentences: [
      { english: 'Excuse me, where is the hospital?', arabic: 'Disculpe, ¿dónde está el hospital?' },
      { english: 'Can you help me please?', arabic: '¿Puede ayudarme, por favor?' },
      { english: 'I am looking for the bank.', arabic: 'Estoy buscando el banco.' },
      { english: 'I am lost. Which way to the park?', arabic: 'Estoy perdido. ¿Por dónde se va al parque?' },
      { english: 'Do you have a map?', arabic: '¿Tienes un mapa?' },
      { english: 'What is your address?', arabic: '¿Cuál es tu dirección?' },
    ],
    exercises: [
      { type: 'mcq', promptAr: 'What is "where" in Spanish?', data: { options: ['Cómo', 'Cuándo', 'Dónde', 'Por qué'], correct: 2 } },
      { type: 'fill_blank', promptAr: 'Complete: ___, ¿dónde está el hospital?', data: { answer: 'Disculpe' } },
      { type: 'translation', promptAr: 'Translate to Spanish: Do you have a map?', data: { answer: '¿Tienes un mapa?', alternatives: ['Tienes un mapa'] } },
      { type: 'matching', promptAr: 'Match the phrases', data: { pairs: [{ english: 'I am lost', arabic: 'Estoy perdido' }, { english: 'Map', arabic: 'Mapa' }, { english: 'Address', arabic: 'Dirección' }, { english: 'Thank you', arabic: 'Gracias' }] } },
      { type: 'reorder', promptAr: 'Arrange: está / dónde / ¿ / el / hospital / ?', data: { words: ['¿Dónde', 'está', 'el', 'hospital', '?'], correctOrder: [0, 1, 2, 3, 4] } },
      { type: 'mcq', promptAr: 'What do you say when you need help finding a place?', data: { options: ['Estoy cansado', 'Estoy buscando', 'Tengo hambre', 'Estoy feliz'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: Estoy ___ el banco. (looking for)', data: { answer: 'buscando' } },
      { type: 'translation', promptAr: 'Translate to Spanish: I am looking for the bank', data: { answer: 'Estoy buscando el banco', alternatives: ['estoy buscando el banco'] } },
    ],
    quiz: [
      { type: 'mcq', promptAr: 'What is "how" in Spanish?', data: { options: ['Dónde', 'Cómo', 'Cuándo', 'Qué'], correct: 1 }, points: 15 },
      { type: 'fill_blank', promptAr: 'Complete: ¿Puede ___ por favor? (help me)', data: { answer: 'ayudarme' }, points: 20 },
      { type: 'matching', promptAr: 'Match the phrases', data: { pairs: [{ english: 'Where', arabic: 'Dónde' }, { english: 'Which way', arabic: 'Por dónde' }, { english: 'Excuse me', arabic: 'Disculpe' }] }, points: 25 },
      { type: 'translation', promptAr: 'Translate to Spanish: I am looking for the bank', data: { answer: 'Estoy buscando el banco', alternatives: ['estoy buscando el banco'] }, points: 25 },
      { type: 'mcq', promptAr: 'What is "I am lost" in Spanish?', data: { options: ['Estoy cansado', 'Estoy perdido', 'Estoy bien', 'Estoy ocupado'], correct: 1 }, points: 15 },
    ]
  },
  'A1-u06-l04': {
    lessonId: 'A1-u06-l04', passingScore: 70,
    vocab: [
      { english: 'Car', arabic: 'Coche / Carro', example: 'Voy al trabajo en coche.', exampleAr: 'I go to work by car.' },
      { english: 'Bus', arabic: 'Autobús', example: 'El autobús viene.', exampleAr: 'The bus is coming.' },
      { english: 'Taxi', arabic: 'Taxi', example: 'Tomo un taxi al aeropuerto.', exampleAr: 'I take a taxi to the airport.' },
      { english: 'Train', arabic: 'Tren', example: 'El tren es rápido.', exampleAr: 'The train is fast.' },
      { english: 'Plane', arabic: 'Avión', example: 'Viajo en avión.', exampleAr: 'I travel by plane.' },
      { english: 'Bicycle', arabic: 'Bicicleta', example: 'Monto en bicicleta.', exampleAr: 'I ride a bicycle.' },
      { english: 'Walk', arabic: 'Caminar', example: 'Me gusta caminar en el parque.', exampleAr: 'I like to walk in the park.' },
      { english: 'Drive', arabic: 'Conducir / Manejar', example: 'Él conduce a la escuela.', exampleAr: 'He drives to school.' },
      { english: 'Station', arabic: 'Estación', example: 'La estación de autobús está cerca.', exampleAr: 'The bus station is near.' },
      { english: 'Airport', arabic: 'Aeropuerto', example: 'El aeropuerto está lejos.', exampleAr: 'The airport is far.' },
    ],
    sentences: [
      { english: 'I go to work by car.', arabic: 'Voy al trabajo en coche.' },
      { english: 'The bus station is near.', arabic: 'La estación de autobús está cerca.' },
      { english: 'I take a taxi to the airport.', arabic: 'Tomo un taxi al aeropuerto.' },
      { english: 'The train is fast.', arabic: 'El tren es rápido.' },
      { english: 'I like to walk in the park.', arabic: 'Me gusta caminar en el parque.' },
      { english: 'He drives to school.', arabic: 'Él conduce a la escuela.' },
    ],
    exercises: [
      { type: 'mcq', promptAr: 'What is "car" in Spanish?', data: { options: ['Autobús', 'Tren', 'Coche', 'Avión'], correct: 2 } },
      { type: 'fill_blank', promptAr: 'Complete: Voy al trabajo en ___. (car)', data: { answer: 'coche' } },
      { type: 'matching', promptAr: 'Match the transport', data: { pairs: [{ english: 'Bus', arabic: 'Autobús' }, { english: 'Train', arabic: 'Tren' }, { english: 'Plane', arabic: 'Avión' }, { english: 'Bicycle', arabic: 'Bicicleta' }] } },
      { type: 'reorder', promptAr: 'Arrange: tren / El / rápido / es', data: { words: ['El', 'tren', 'es', 'rápido'], correctOrder: [0, 1, 2, 3] } },
      { type: 'translation', promptAr: 'Translate to Spanish: The train is fast', data: { answer: 'El tren es rápido', alternatives: ['el tren es rápido'] } },
      { type: 'mcq', promptAr: 'Where do planes land?', data: { options: ['Estación', 'Hospital', 'Aeropuerto', 'Escuela'], correct: 2 } },
      { type: 'fill_blank', promptAr: 'Complete: La ___ de autobús está cerca. (station)', data: { answer: 'estación' } },
      { type: 'mcq', promptAr: 'What is "station" in Spanish?', data: { options: ['Aeropuerto', 'Estación', 'Autobús', 'Tren'], correct: 1 } },
    ],
    quiz: [
      { type: 'mcq', promptAr: 'What is "taxi" in Spanish?', data: { options: ['Autobús', 'Taxi', 'Tren', 'Coche'], correct: 1 }, points: 15 },
      { type: 'fill_blank', promptAr: 'Complete: Tomo un ___ al aeropuerto. (taxi)', data: { answer: 'taxi' }, points: 20 },
      { type: 'matching', promptAr: 'Match the words', data: { pairs: [{ english: 'Walk', arabic: 'Caminar' }, { english: 'Drive', arabic: 'Conducir' }, { english: 'Station', arabic: 'Estación' }] }, points: 25 },
      { type: 'translation', promptAr: 'Translate to Spanish: I like to walk in the park', data: { answer: 'Me gusta caminar en el parque', alternatives: ['me gusta caminar en el parque'] }, points: 25 },
      { type: 'mcq', promptAr: 'What is "airport" in Spanish?', data: { options: ['Estación', 'Aeropuerto', 'Hospital', 'Escuela'], correct: 1 }, points: 15 },
    ]
  },
  'A1-u06-l05': {
    lessonId: 'A1-u06-l05', passingScore: 70,
    vocab: [
      { english: 'City', arabic: 'Ciudad', example: 'La ciudad es grande.', exampleAr: 'The city is big.' },
      { english: 'Street', arabic: 'Calle', example: 'Vivo en una calle tranquila.', exampleAr: 'I live on a quiet street.' },
      { english: 'Building', arabic: 'Edificio', example: 'El edificio es alto.', exampleAr: 'The building is tall.' },
      { english: 'Bridge', arabic: 'Puente', example: 'Cruza el puente.', exampleAr: 'Cross the bridge.' },
      { english: 'Traffic', arabic: 'Tráfico', example: 'Hay mucho tráfico.', exampleAr: 'There is a lot of traffic.' },
      { english: 'Traffic light', arabic: 'Semáforo', example: 'Espera en el semáforo.', exampleAr: 'Wait at the traffic light.' },
      { english: 'Crosswalk', arabic: 'Paso de peatones', example: 'Cruza en el paso de peatones.', exampleAr: 'Cross at the crosswalk.' },
      { english: 'Downtown', arabic: 'Centro', example: 'Trabajo en el centro.', exampleAr: 'I work downtown.' },
      { english: 'Neighborhood', arabic: 'Barrio / Vecindario', example: 'Este es un buen barrio.', exampleAr: 'This is a nice neighborhood.' },
      { english: 'Square', arabic: 'Plaza', example: 'Nos vemos en la plaza.', exampleAr: 'Meet me at the square.' },
    ],
    sentences: [
      { english: 'The city is big.', arabic: 'La ciudad es grande.' },
      { english: 'I live on a quiet street.', arabic: 'Vivo en una calle tranquila.' },
      { english: 'There is a lot of traffic downtown.', arabic: 'Hay mucho tráfico en el centro.' },
      { english: 'Wait at the traffic light.', arabic: 'Espera en el semáforo.' },
      { english: 'The building is tall.', arabic: 'El edificio es alto.' },
      { english: 'Cross at the crosswalk.', arabic: 'Cruza en el paso de peatones.' },
    ],
    exercises: [
      { type: 'mcq', promptAr: 'What is "city" in Spanish?', data: { options: ['Pueblo', 'Ciudad', 'Barrio', 'Calle'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: La ___ es grande. (city)', data: { answer: 'ciudad' } },
      { type: 'translation', promptAr: 'Translate to Spanish: I live on a quiet street', data: { answer: 'Vivo en una calle tranquila', alternatives: ['vivo en una calle tranquila'] } },
      { type: 'matching', promptAr: 'Match the words', data: { pairs: [{ english: 'Street', arabic: 'Calle' }, { english: 'Building', arabic: 'Edificio' }, { english: 'Bridge', arabic: 'Puente' }, { english: 'Square', arabic: 'Plaza' }] } },
      { type: 'reorder', promptAr: 'Arrange: tráfico / Hay / mucho', data: { words: ['Hay', 'mucho', 'tráfico'], correctOrder: [0, 1, 2] } },
      { type: 'mcq', promptAr: 'What is "traffic light" in Spanish?', data: { options: ['Tráfico', 'Semáforo', 'Puente', 'Calle'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: Espera en el ___. (traffic light)', data: { answer: 'semáforo' } },
      { type: 'translation', promptAr: 'Translate to Spanish: The building is tall', data: { answer: 'El edificio es alto', alternatives: ['el edificio es alto'] } },
    ],
    quiz: [
      { type: 'mcq', promptAr: 'What is "street" in Spanish?', data: { options: ['Avenida', 'Calle', 'Camino', 'Plaza'], correct: 1 }, points: 15 },
      { type: 'fill_blank', promptAr: 'Complete: Trabajo en el ___. (downtown)', data: { answer: 'centro' }, points: 20 },
      { type: 'matching', promptAr: 'Match the words', data: { pairs: [{ english: 'Traffic', arabic: 'Tráfico' }, { english: 'Neighborhood', arabic: 'Barrio' }, { english: 'Downtown', arabic: 'Centro' }] }, points: 25 },
      { type: 'translation', promptAr: 'Translate to Spanish: There is a lot of traffic', data: { answer: 'Hay mucho tráfico', alternatives: ['hay mucho tráfico'] }, points: 25 },
      { type: 'mcq', promptAr: 'What is "square" in Spanish?', data: { options: ['Parque', 'Plaza', 'Calle', 'Barrio'], correct: 1 }, points: 15 },
    ]
  },
};

export const a1Unit6Lessons = lessons;
