// A1 Unit 7: Daily Routine — Spanish for English Speakers
import { LessonContent } from './a1-lessons';

const lessons: Record<string, LessonContent> = {
  'A1-u07-l01': {
    lessonId: 'A1-u07-l01', passingScore: 70,
    vocab: [
      { english: 'Wake up', arabic: 'Despertarse', example: 'Me despierto a las 6.', exampleAr: 'I wake up at 6.' },
      { english: 'Get up', arabic: 'Levantarse', example: 'Me levanto temprano.', exampleAr: 'I get up early.' },
      { english: 'Brush teeth', arabic: 'Cepillarse los dientes', example: 'Me cepillo los dientes cada mañana.', exampleAr: 'I brush my teeth every morning.' },
      { english: 'Take a shower', arabic: 'Ducharse', example: 'Me ducho antes del desayuno.', exampleAr: 'I take a shower before breakfast.' },
      { english: 'Get dressed', arabic: 'Vestirse', example: 'Me visto rápido.', exampleAr: 'I get dressed quickly.' },
      { english: 'Have breakfast', arabic: 'Desayunar', example: 'Desayuno a las 7.', exampleAr: 'I have breakfast at 7.' },
      { english: 'Morning', arabic: 'Mañana', example: '¡Buenos días!', exampleAr: 'Good morning!' },
      { english: 'Early', arabic: 'Temprano', example: 'Me despierto temprano.', exampleAr: 'I wake up early.' },
      { english: 'Late', arabic: 'Tarde', example: 'Llego tarde al trabajo.', exampleAr: 'I am late for work.' },
      { english: 'Alarm', arabic: 'Alarma / Despertador', example: 'La alarma suena a las 5:30.', exampleAr: 'The alarm rings at 5:30.' },
    ],
    sentences: [
      { english: 'I wake up at 6 AM.', arabic: 'Me despierto a las 6 de la mañana.' },
      { english: 'I brush my teeth every morning.', arabic: 'Me cepillo los dientes cada mañana.' },
      { english: 'I take a shower before breakfast.', arabic: 'Me ducho antes del desayuno.' },
      { english: 'I get dressed quickly.', arabic: 'Me visto rápido.' },
      { english: 'I have breakfast with my family.', arabic: 'Desayuno con mi familia.' },
      { english: 'The alarm rings at 5:30.', arabic: 'La alarma suena a las 5:30.' },
    ],
    exercises: [
      { type: 'mcq', promptAr: 'What is "wake up" in Spanish?', data: { options: ['Dormir', 'Despertarse', 'Comer', 'Beber'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: Me ___ a las 6. (wake up)', data: { answer: 'despierto' } },
      { type: 'matching', promptAr: 'Match the morning activities', data: { pairs: [{ english: 'Take a shower', arabic: 'Ducharse' }, { english: 'Get dressed', arabic: 'Vestirse' }, { english: 'Have breakfast', arabic: 'Desayunar' }, { english: 'Alarm', arabic: 'Alarma' }] } },
      { type: 'reorder', promptAr: 'Arrange: dientes / Me / los / cepillo / mañana / cada', data: { words: ['Me', 'cepillo', 'los', 'dientes', 'cada', 'mañana'], correctOrder: [0, 1, 2, 3, 4, 5] } },
      { type: 'translation', promptAr: 'Translate to Spanish: I get dressed quickly', data: { answer: 'Me visto rápido', alternatives: ['me visto rápido'] } },
      { type: 'mcq', promptAr: 'What do you do first in the morning?', data: { options: ['Cenar', 'Dormir', 'Despertarse', 'Ver la tele'], correct: 2 } },
      { type: 'fill_blank', promptAr: 'Complete: Me ___ antes del desayuno. (shower)', data: { answer: 'ducho' } },
      { type: 'mcq', promptAr: 'What is "get up" in Spanish?', data: { options: ['Cepillarse', 'Ducharse', 'Levantarse', 'Despertarse'], correct: 2 } },
    ],
    quiz: [
      { type: 'mcq', promptAr: 'What is "morning" in Spanish?', data: { options: ['Noche', 'Tarde', 'Mañana', 'Mediodía'], correct: 2 }, points: 15 },
      { type: 'fill_blank', promptAr: 'Complete: Me ___ rápido. (get dressed)', data: { answer: 'visto' }, points: 20 },
      { type: 'matching', promptAr: 'Match the words', data: { pairs: [{ english: 'Early', arabic: 'Temprano' }, { english: 'Late', arabic: 'Tarde' }, { english: 'Get up', arabic: 'Levantarse' }] }, points: 25 },
      { type: 'translation', promptAr: 'Translate to Spanish: I have breakfast with my family', data: { answer: 'Desayuno con mi familia', alternatives: ['desayuno con mi familia'] }, points: 25 },
      { type: 'mcq', promptAr: 'What is "take a shower" in Spanish?', data: { options: ['Cepillarse', 'Ducharse', 'Vestirse', 'Despertarse'], correct: 1 }, points: 15 },
    ]
  },
  'A1-u07-l02': {
    lessonId: 'A1-u07-l02', passingScore: 70,
    vocab: [
      { english: 'Leave home', arabic: 'Salir de casa', example: 'Salgo de casa a las 7:30.', exampleAr: 'I leave home at 7:30.' },
      { english: 'Arrive', arabic: 'Llegar', example: 'Llego al trabajo a las 8.', exampleAr: 'I arrive at work at 8.' },
      { english: 'Commute', arabic: 'Desplazamiento', example: 'Mi desplazamiento dura 30 minutos.', exampleAr: 'My commute takes 30 minutes.' },
      { english: 'Traffic jam', arabic: 'Atasco / Embotellamiento', example: 'Hay un atasco.', exampleAr: 'There is a traffic jam.' },
      { english: 'On time', arabic: 'A tiempo / Puntual', example: 'Intento llegar a tiempo.', exampleAr: 'I try to be on time.' },
      { english: 'Rush hour', arabic: 'Hora punta', example: 'La hora punta es muy ocupada.', exampleAr: 'Rush hour is busy.' },
      { english: 'Catch the bus', arabic: 'Coger el autobús', example: 'Cojo el autobús a las 7.', exampleAr: 'I catch the bus at 7.' },
      { english: 'Miss the bus', arabic: 'Perder el autobús', example: 'Perdí el autobús hoy.', exampleAr: 'I missed the bus today.' },
      { english: 'Lunch break', arabic: 'Pausa para el almuerzo', example: 'La pausa es a las 12:30.', exampleAr: 'Lunch break is at 12:30.' },
      { english: 'Meeting', arabic: 'Reunión', example: 'Tengo una reunión a las 10.', exampleAr: 'I have a meeting at 10.' },
    ],
    sentences: [
      { english: 'I leave home at 7:30.', arabic: 'Salgo de casa a las 7:30.' },
      { english: 'I arrive at work at 8 AM.', arabic: 'Llego al trabajo a las 8.' },
      { english: 'There is a traffic jam every morning.', arabic: 'Hay un atasco cada mañana.' },
      { english: 'I try to be on time.', arabic: 'Intento llegar a tiempo.' },
      { english: 'I have a meeting at 10.', arabic: 'Tengo una reunión a las 10.' },
      { english: 'Lunch break is at 12:30.', arabic: 'La pausa para el almuerzo es a las 12:30.' },
    ],
    exercises: [
      { type: 'mcq', promptAr: 'What is "leave home" in Spanish?', data: { options: ['Llegar', 'Salir de casa', 'Dormir', 'Comer'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: ___ de casa a las 7:30. (I leave)', data: { answer: 'Salgo' } },
      { type: 'matching', promptAr: 'Match the phrases', data: { pairs: [{ english: 'Traffic jam', arabic: 'Atasco' }, { english: 'On time', arabic: 'A tiempo' }, { english: 'Rush hour', arabic: 'Hora punta' }, { english: 'Meeting', arabic: 'Reunión' }] } },
      { type: 'translation', promptAr: 'Translate to Spanish: I have a meeting at 10', data: { answer: 'Tengo una reunión a las 10', alternatives: ['tengo una reunión a las 10'] } },
      { type: 'mcq', promptAr: 'What is "arrive" in Spanish?', data: { options: ['Salir', 'Llegar', 'Ir', 'Venir'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: Intento llegar a ___. (time)', data: { answer: 'tiempo' } },
      { type: 'reorder', promptAr: 'Arrange: al / Llego / trabajo / las / a / 8', data: { words: ['Llego', 'al', 'trabajo', 'a', 'las', '8'], correctOrder: [0, 1, 2, 3, 4, 5] } },
      { type: 'mcq', promptAr: 'What happens when there is a lot of traffic?', data: { options: ['Atasco', 'Pausa', 'Reunión', 'Puntual'], correct: 0 } },
    ],
    quiz: [
      { type: 'mcq', promptAr: 'What is "arrive" in Spanish?', data: { options: ['Salir', 'Llegar', 'Ir', 'Volver'], correct: 1 }, points: 15 },
      { type: 'fill_blank', promptAr: 'Complete: Tengo una ___ a las 10. (meeting)', data: { answer: 'reunión' }, points: 20 },
      { type: 'matching', promptAr: 'Match the phrases', data: { pairs: [{ english: 'Catch the bus', arabic: 'Coger el autobús' }, { english: 'Miss the bus', arabic: 'Perder el autobús' }, { english: 'Commute', arabic: 'Desplazamiento' }] }, points: 25 },
      { type: 'translation', promptAr: 'Translate to Spanish: There is a traffic jam every morning', data: { answer: 'Hay un atasco cada mañana', alternatives: ['hay un atasco cada mañana'] }, points: 25 },
      { type: 'mcq', promptAr: 'What is "traffic jam" in Spanish?', data: { options: ['Hora punta', 'Atasco', 'Puntual', 'Desplazamiento'], correct: 1 }, points: 15 },
    ]
  },
  'A1-u07-l03': {
    lessonId: 'A1-u07-l03', passingScore: 70,
    vocab: [
      { english: 'Come home', arabic: 'Volver a casa', example: 'Vuelvo a casa a las 5.', exampleAr: 'I come home at 5.' },
      { english: 'Rest', arabic: 'Descansar', example: 'Descanso una hora.', exampleAr: 'I rest for an hour.' },
      { english: 'Have dinner', arabic: 'Cenar', example: 'Cenamos a las 7.', exampleAr: 'We have dinner at 7.' },
      { english: 'Watch TV', arabic: 'Ver la tele', example: 'Veo la tele con mi familia.', exampleAr: 'I watch TV with my family.' },
      { english: 'Read a book', arabic: 'Leer un libro', example: 'Leo un libro antes de dormir.', exampleAr: 'I read a book before bed.' },
      { english: 'Spend time', arabic: 'Pasar tiempo', example: 'Paso tiempo con la familia.', exampleAr: 'I spend time with family.' },
      { english: 'Evening', arabic: 'Noche / Tarde', example: '¡Buenas noches!', exampleAr: 'Good evening!' },
      { english: 'Tired', arabic: 'Cansado/a', example: 'Estoy cansado después del trabajo.', exampleAr: 'I am tired after work.' },
      { english: 'Relax', arabic: 'Relajarse', example: 'Me relajo en el sofá.', exampleAr: 'I relax on the sofa.' },
      { english: 'Homework', arabic: 'Tarea', example: 'Hago mi tarea.', exampleAr: 'I do my homework.' },
    ],
    sentences: [
      { english: 'I come home at 5 PM.', arabic: 'Vuelvo a casa a las 5 de la tarde.' },
      { english: 'I rest for an hour.', arabic: 'Descanso una hora.' },
      { english: 'We have dinner at 7 PM.', arabic: 'Cenamos a las 7 de la noche.' },
      { english: 'I watch TV with my family.', arabic: 'Veo la tele con mi familia.' },
      { english: 'I do my homework before dinner.', arabic: 'Hago mi tarea antes de cenar.' },
      { english: 'I am tired after work.', arabic: 'Estoy cansado después del trabajo.' },
    ],
    exercises: [
      { type: 'mcq', promptAr: 'What is "come home" in Spanish?', data: { options: ['Ir', 'Volver a casa', 'Dormir', 'Comer'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: ___ a casa a las 5. (I come back)', data: { answer: 'Vuelvo' } },
      { type: 'matching', promptAr: 'Match evening activities', data: { pairs: [{ english: 'Rest', arabic: 'Descansar' }, { english: 'Have dinner', arabic: 'Cenar' }, { english: 'Relax', arabic: 'Relajarse' }, { english: 'Tired', arabic: 'Cansado' }] } },
      { type: 'translation', promptAr: 'Translate to Spanish: I watch TV with my family', data: { answer: 'Veo la tele con mi familia', alternatives: ['veo la tele con mi familia'] } },
      { type: 'mcq', promptAr: 'What do students do after school?', data: { options: ['Ir al trabajo', 'Hacer la tarea', 'Despertarse', 'Desayunar'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: Estoy ___ después del trabajo. (tired)', data: { answer: 'cansado' } },
      { type: 'reorder', promptAr: 'Arrange: tele / la / Veo / familia / mi / con', data: { words: ['Veo', 'la', 'tele', 'con', 'mi', 'familia'], correctOrder: [0, 1, 2, 3, 4, 5] } },
      { type: 'mcq', promptAr: 'What is "watch TV" in Spanish?', data: { options: ['Leer un libro', 'Ver la tele', 'Cenar', 'Descansar'], correct: 1 } },
    ],
    quiz: [
      { type: 'mcq', promptAr: 'What is "rest" in Spanish?', data: { options: ['Trabajar', 'Descansar', 'Comer', 'Beber'], correct: 1 }, points: 15 },
      { type: 'fill_blank', promptAr: 'Complete: ___ a las 7. (We have dinner)', data: { answer: 'Cenamos' }, points: 20 },
      { type: 'matching', promptAr: 'Match the words', data: { pairs: [{ english: 'Read a book', arabic: 'Leer un libro' }, { english: 'Spend time', arabic: 'Pasar tiempo' }, { english: 'Evening', arabic: 'Noche' }] }, points: 25 },
      { type: 'translation', promptAr: 'Translate to Spanish: I do my homework before dinner', data: { answer: 'Hago mi tarea antes de cenar', alternatives: ['hago mi tarea antes de cenar'] }, points: 25 },
      { type: 'mcq', promptAr: 'What is "homework" in Spanish?', data: { options: ['Trabajo de casa', 'Tarea', 'Trabajo', 'Escuela'], correct: 1 }, points: 15 },
    ]
  },
  'A1-u07-l04': {
    lessonId: 'A1-u07-l04', passingScore: 70,
    vocab: [
      { english: 'Go to bed', arabic: 'Irse a la cama / Acostarse', example: 'Me acuesto a las 10.', exampleAr: 'I go to bed at 10.' },
      { english: 'Sleep', arabic: 'Dormir', example: 'Duermo 8 horas.', exampleAr: 'I sleep 8 hours.' },
      { english: 'Pajamas', arabic: 'Pijama', example: 'Me pongo el pijama.', exampleAr: 'I put on my pajamas.' },
      { english: 'Dream', arabic: 'Sueño / Soñar', example: 'Tuve un buen sueño.', exampleAr: 'I had a good dream.' },
      { english: 'Night', arabic: 'Noche', example: '¡Buenas noches!', exampleAr: 'Good night!' },
      { english: 'Midnight', arabic: 'Medianoche', example: 'Dormí a medianoche.', exampleAr: 'I slept at midnight.' },
      { english: 'Set the alarm', arabic: 'Poner la alarma', example: 'Pongo la alarma para mañana.', exampleAr: 'I set the alarm for tomorrow.' },
      { english: 'Turn off the light', arabic: 'Apagar la luz', example: 'Apago la luz.', exampleAr: 'I turn off the light.' },
      { english: 'Good night', arabic: 'Buenas noches', example: 'Buenas noches, ¡duerme bien!', exampleAr: 'Good night, sleep well!' },
      { english: 'Sweet dreams', arabic: 'Dulces sueños', example: '¡Dulces sueños!', exampleAr: 'Sweet dreams!' },
    ],
    sentences: [
      { english: 'I go to bed at 10 PM.', arabic: 'Me acuesto a las 10 de la noche.' },
      { english: 'I put on my pajamas.', arabic: 'Me pongo el pijama.' },
      { english: 'I set the alarm for tomorrow.', arabic: 'Pongo la alarma para mañana.' },
      { english: 'I turn off the light.', arabic: 'Apago la luz.' },
      { english: 'Good night, sweet dreams!', arabic: '¡Buenas noches, dulces sueños!' },
      { english: 'I sleep 8 hours every night.', arabic: 'Duermo 8 horas cada noche.' },
    ],
    exercises: [
      { type: 'mcq', promptAr: 'What is "go to bed" in Spanish?', data: { options: ['Despertarse', 'Acostarse', 'Comer', 'Leer'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: Me ___ a las 10. (go to bed)', data: { answer: 'acuesto' } },
      { type: 'matching', promptAr: 'Match bedtime words', data: { pairs: [{ english: 'Pajamas', arabic: 'Pijama' }, { english: 'Dream', arabic: 'Sueño' }, { english: 'Night', arabic: 'Noche' }, { english: 'Midnight', arabic: 'Medianoche' }] } },
      { type: 'translation', promptAr: 'Translate to Spanish: Sweet dreams', data: { answer: 'Dulces sueños', alternatives: ['dulces sueños'] } },
      { type: 'reorder', promptAr: 'Arrange: la / Apago / luz', data: { words: ['Apago', 'la', 'luz'], correctOrder: [0, 1, 2] } },
      { type: 'mcq', promptAr: 'What do you say before going to sleep?', data: { options: ['Buenos días', 'Buenas noches', 'Buenas tardes', 'Hola'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: Pongo la ___ para mañana. (alarm)', data: { answer: 'alarma' } },
      { type: 'mcq', promptAr: 'What is "sleep" in Spanish?', data: { options: ['Despertarse', 'Dormir', 'Soñar', 'Descansar'], correct: 1 } },
    ],
    quiz: [
      { type: 'mcq', promptAr: 'What is "sleep" in Spanish?', data: { options: ['Despertarse', 'Dormir', 'Soñar', 'Descansar'], correct: 1 }, points: 15 },
      { type: 'fill_blank', promptAr: 'Complete: Me pongo el ___. (pajamas)', data: { answer: 'pijama' }, points: 20 },
      { type: 'matching', promptAr: 'Match the phrases', data: { pairs: [{ english: 'Good night', arabic: 'Buenas noches' }, { english: 'Set the alarm', arabic: 'Poner la alarma' }, { english: 'Turn off the light', arabic: 'Apagar la luz' }] }, points: 25 },
      { type: 'translation', promptAr: 'Translate to Spanish: I sleep 8 hours every night', data: { answer: 'Duermo 8 horas cada noche', alternatives: ['duermo 8 horas cada noche'] }, points: 25 },
      { type: 'mcq', promptAr: 'What is "night" in Spanish?', data: { options: ['Mañana', 'Tarde', 'Mediodía', 'Noche'], correct: 3 }, points: 15 },
    ]
  },
  'A1-u07-l05': {
    lessonId: 'A1-u07-l05', passingScore: 70,
    vocab: [
      { english: 'Weekend', arabic: 'Fin de semana', example: 'Me encanta el fin de semana.', exampleAr: 'I love the weekend.' },
      { english: 'Saturday', arabic: 'Sábado', example: 'Descanso el sábado.', exampleAr: 'I relax on Saturday.' },
      { english: 'Sunday', arabic: 'Domingo', example: 'Visito amigos el domingo.', exampleAr: 'I visit friends on Sunday.' },
      { english: 'Sleep in', arabic: 'Dormir hasta tarde', example: 'Duermo hasta tarde los fines de semana.', exampleAr: 'I sleep in on weekends.' },
      { english: 'Go out', arabic: 'Salir', example: 'Salgo con amigos.', exampleAr: 'I go out with friends.' },
      { english: 'Visit friends', arabic: 'Visitar amigos', example: 'Visito amigos el domingo.', exampleAr: 'I visit friends on Sunday.' },
      { english: 'Play sports', arabic: 'Hacer deporte', example: 'Hago deporte el sábado.', exampleAr: 'I play sports on Saturday.' },
      { english: 'Watch a movie', arabic: 'Ver una película', example: 'Vemos una película.', exampleAr: 'We watch a movie.' },
      { english: 'Go shopping', arabic: 'Ir de compras', example: 'Voy de compras el sábado.', exampleAr: 'I go shopping on Saturday.' },
      { english: 'Enjoy', arabic: 'Disfrutar', example: 'Disfruto del fin de semana.', exampleAr: 'I enjoy the weekend.' },
    ],
    sentences: [
      { english: 'I love the weekend.', arabic: 'Me encanta el fin de semana.' },
      { english: 'I sleep in on Saturday.', arabic: 'Duermo hasta tarde el sábado.' },
      { english: 'I go out with friends on Sunday.', arabic: 'Salgo con amigos el domingo.' },
      { english: 'I play sports every weekend.', arabic: 'Hago deporte cada fin de semana.' },
      { english: 'We watch a movie on Saturday night.', arabic: 'Vemos una película el sábado por la noche.' },
      { english: 'I enjoy spending time with my family.', arabic: 'Disfruto pasando tiempo con mi familia.' },
    ],
    exercises: [
      { type: 'mcq', promptAr: 'What is "weekend" in Spanish?', data: { options: ['Semana', 'Fin de semana', 'Día festivo', 'Vacaciones'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: ___ con amigos el domingo. (I go out)', data: { answer: 'Salgo' } },
      { type: 'matching', promptAr: 'Match weekend activities', data: { pairs: [{ english: 'Go out', arabic: 'Salir' }, { english: 'Play sports', arabic: 'Hacer deporte' }, { english: 'Watch a movie', arabic: 'Ver una película' }, { english: 'Go shopping', arabic: 'Ir de compras' }] } },
      { type: 'translation', promptAr: 'Translate to Spanish: I love the weekend', data: { answer: 'Me encanta el fin de semana', alternatives: ['me encanta el fin de semana'] } },
      { type: 'mcq', promptAr: 'What is "go shopping" in Spanish?', data: { options: ['Salir', 'Ir de compras', 'Hacer deporte', 'Ver la tele'], correct: 1 } },
      { type: 'fill_blank', promptAr: 'Complete: ___ deporte cada fin de semana. (I do)', data: { answer: 'Hago' } },
      { type: 'reorder', promptAr: 'Arrange: película / Vemos / una', data: { words: ['Vemos', 'una', 'película'], correctOrder: [0, 1, 2] } },
      { type: 'mcq', promptAr: 'What is "enjoy" in Spanish?', data: { options: ['Trabajar', 'Disfrutar', 'Dormir', 'Comer'], correct: 1 } },
    ],
    quiz: [
      { type: 'mcq', promptAr: 'What is "sleep in" in Spanish?', data: { options: ['Despertarse', 'Dormir temprano', 'Dormir hasta tarde', 'Acostarse'], correct: 2 }, points: 15 },
      { type: 'translation', promptAr: 'Translate to Spanish: I go out with friends', data: { answer: 'Salgo con amigos', alternatives: ['Yo salgo con amigos'] }, points: 20 },
      { type: 'fill_blank', promptAr: 'Complete: ___ del fin de semana. (I enjoy)', data: { answer: 'Disfruto' }, points: 15 },
      { type: 'matching', promptAr: 'Match the words', data: { pairs: [{ english: 'Saturday', arabic: 'Sábado' }, { english: 'Sunday', arabic: 'Domingo' }, { english: 'Visit friends', arabic: 'Visitar amigos' }] }, points: 25 },
      { type: 'translation', promptAr: 'Translate to Spanish: We watch a movie on Saturday', data: { answer: 'Vemos una película el sábado', alternatives: ['vemos una película el sábado'] }, points: 25 },
    ]
  },
};

export const a1Unit7Lessons = lessons;
